"""Tests for report generation."""

import pandas as pd
import pytest
from click.testing import CliRunner

from transparency_engine.cli import cli
from transparency_engine.config import OutputFormat, PeriodSpec
from transparency_engine.reports.generator import ReportGenerator


@pytest.fixture
def report_data():
    return pd.DataFrame(
        [
            {"metric_id": "notices_received", "period": "2024-H1", "value": 284750},
            {"metric_id": "notices_actioned", "period": "2024-H1", "value": 213562},
            {"metric_id": "notices_median_response_time", "period": "2024-H1", "value": 4.2},
            {"metric_id": "complaints_received", "period": "2024-H1", "value": 47830},
            {"metric_id": "complaints_reversed", "period": "2024-H1", "value": 6214},
            {"metric_id": "content_moderation_orders_received", "period": "2024-H1", "value": 342},
        ]
    )


@pytest.fixture
def generator(dsa_framework, report_data):
    period = PeriodSpec.parse("2024-H1")
    return ReportGenerator(
        framework=dsa_framework,
        period=period,
        data=report_data,
        platform_name="TestPlatform",
    )


class TestReportGenerator:
    def test_generate_html(self, generator, tmp_path):
        path = tmp_path / "report.html"
        content = generator.generate(OutputFormat.HTML, output_path=path)
        assert "<html" in content
        assert "TestPlatform" in content
        assert "2024-H1" in content
        assert path.exists()

    def test_generate_markdown(self, generator):
        content = generator.generate(OutputFormat.MARKDOWN)
        assert "# EU Digital Services Act Transparency Report" in content
        assert "TestPlatform" in content
        assert "284.8K" in content or "284,750" in content

    def test_generate_json(self, generator):
        import json

        content = generator.generate(OutputFormat.JSON)
        data = json.loads(content)
        assert data["framework_name"] == "EU Digital Services Act"
        assert data["platform_name"] == "TestPlatform"
        assert len(data["sections"]) > 0

    def test_metadata_in_json(self, generator):
        import json

        from transparency_engine import __version__

        data = json.loads(generator.generate(OutputFormat.JSON))
        assert data["engine_version"] == __version__
        assert "generated_at" in data
        assert data["generated_at"]  # non-empty

    def test_metadata_in_markdown(self, generator):
        from transparency_engine import __version__

        content = generator.generate(OutputFormat.MARKDOWN)
        assert f"v{__version__}" in content
        assert "Generated by transparency-engine" in content

    def test_metadata_in_html(self, generator):
        from transparency_engine import __version__

        content = generator.generate(OutputFormat.HTML)
        assert f"v{__version__}" in content
        assert "transparency-engine" in content

    def test_generate_with_comparison(self, dsa_framework, report_data):
        prev_data = pd.DataFrame(
            [
                {"metric_id": "notices_received", "period": "2023-H2", "value": 251400},
                {"metric_id": "notices_actioned", "period": "2023-H2", "value": 188550},
            ]
        )
        period = PeriodSpec.parse("2024-H1")
        gen = ReportGenerator(
            framework=dsa_framework,
            period=period,
            data=report_data,
            platform_name="TestPlatform",
            previous_period_data=prev_data,
        )
        content = gen.generate(OutputFormat.MARKDOWN)
        assert "Period Comparison" in content

    def test_format_value_large(self, generator):
        assert ReportGenerator._format_value(1_500_000) == "1.5M"
        assert ReportGenerator._format_value(42_000) == "42.0K"
        assert ReportGenerator._format_value(500) == "500"
        assert ReportGenerator._format_value(3.14) == "3.14"

    def test_output_to_file(self, generator, tmp_path):
        path = tmp_path / "subdir" / "report.md"
        generator.generate(OutputFormat.MARKDOWN, output_path=path)
        assert path.exists()
        content = path.read_text()
        assert "TestPlatform" in content

    def test_pdf_requires_output_path(self, generator):
        with pytest.raises(ValueError, match="output_path is required"):
            generator.generate(OutputFormat.PDF)

    def test_generate_csv_basic(self, generator):
        import csv as csv_mod
        import io

        content = generator.generate(OutputFormat.CSV)
        reader = csv_mod.DictReader(io.StringIO(content))
        rows = list(reader)
        assert len(rows) > 0
        assert rows[0]["table"] == "metrics"
        assert rows[0]["period"] == "2024-H1"
        metric_ids = {r["metric_id"] for r in rows}
        assert "notices_received" in metric_ids

    def test_generate_csv_includes_formatted_value(self, generator):
        import csv as csv_mod
        import io

        content = generator.generate(OutputFormat.CSV)
        reader = csv_mod.DictReader(io.StringIO(content))
        rows = [r for r in reader if r["metric_id"] == "notices_received"]
        assert len(rows) == 1
        assert rows[0]["formatted_value"] == "284.8K"

    def test_generate_csv_with_comparison(self, dsa_framework, report_data):
        import csv as csv_mod
        import io

        prev_data = pd.DataFrame(
            [
                {"metric_id": "notices_received", "period": "2023-H2", "value": 251400},
                {"metric_id": "notices_actioned", "period": "2023-H2", "value": 188550},
            ]
        )
        period = PeriodSpec.parse("2024-H1")
        gen = ReportGenerator(
            framework=dsa_framework,
            period=period,
            data=report_data,
            platform_name="TestPlatform",
            previous_period_data=prev_data,
        )
        content = gen.generate(OutputFormat.CSV)
        lines = content.strip().splitlines()
        # There should be a blank separator line between the two tables
        assert "" in lines
        # Parse all non-blank, non-header rows
        all_rows: list[dict] = []
        for chunk in content.split("\r\n\r\n") + content.split("\n\n"):
            chunk = chunk.strip()
            if not chunk:
                continue
            reader = csv_mod.DictReader(io.StringIO(chunk))
            all_rows.extend(list(reader))
        tables = {r["table"] for r in all_rows}
        assert "metrics" in tables
        assert "comparison" in tables
        comparison_rows = [r for r in all_rows if r["table"] == "comparison"]
        assert any(r["metric_id"] == "notices_received" for r in comparison_rows)

    def test_generate_csv_no_comparison_section_when_no_prev_data(self, generator):
        content = generator.generate(OutputFormat.CSV)
        assert "comparison" not in content


class TestPeriodSpecYoY:
    def test_yoy_period_half_year(self):
        period = PeriodSpec.parse("2024-H1")
        yoy = period.yoy_period()
        assert yoy.year == 2023
        assert yoy.label == "H1"
        assert str(yoy) == "2023-H1"

    def test_yoy_period_quarterly(self):
        period = PeriodSpec.parse("2025-Q3")
        yoy = period.yoy_period()
        assert str(yoy) == "2024-Q3"

    def test_yoy_period_full_year(self):
        period = PeriodSpec.parse("2024-FY")
        yoy = period.yoy_period()
        assert str(yoy) == "2023-FY"

    def test_yoy_period_does_not_mutate_original(self):
        period = PeriodSpec.parse("2024-H2")
        _ = period.yoy_period()
        assert str(period) == "2024-H2"


class TestGenerateCLIComparison:
    """Tests for --yoy and --compare-period flags in the generate command."""

    @pytest.fixture
    def multi_period_csv(self, tmp_path):
        """CSV with data for both 2024-H1 and 2023-H1."""
        rows = [
            "metric_id,period,value",
            "notices_received,2024-H1,284750",
            "notices_actioned,2024-H1,213562",
            "complaints_received,2024-H1,47830",
            "complaints_reversed,2024-H1,6214",
            "content_moderation_orders_received,2024-H1,342",
            "notices_median_response_time,2024-H1,4.2",
            "notices_received,2023-H1,241000",
            "notices_actioned,2023-H1,180750",
            "complaints_received,2023-H1,39200",
            "complaints_reversed,2023-H1,5100",
        ]
        path = tmp_path / "metrics.csv"
        path.write_text("\n".join(rows))
        return str(path)

    def test_generate_with_yoy_flag(self, multi_period_csv, tmp_path):
        runner = CliRunner()
        out_path = str(tmp_path / "report.md")
        result = runner.invoke(
            cli,
            [
                "generate",
                "--framework",
                "dsa",
                "--period",
                "2024-H1",
                "--data",
                multi_period_csv,
                "--format",
                "markdown",
                "--output",
                out_path,
                "--yoy",
            ],
        )
        assert result.exit_code == 0, result.output
        assert "2024-H1 vs 2023-H1" in result.output
        content = open(out_path).read()
        assert "Period Comparison" in content

    def test_generate_with_compare_period(self, multi_period_csv, tmp_path):
        runner = CliRunner()
        out_path = str(tmp_path / "report.md")
        result = runner.invoke(
            cli,
            [
                "generate",
                "--framework",
                "dsa",
                "--period",
                "2024-H1",
                "--data",
                multi_period_csv,
                "--format",
                "markdown",
                "--output",
                out_path,
                "--compare-period",
                "2023-H1",
            ],
        )
        assert result.exit_code == 0, result.output
        assert "2024-H1 vs 2023-H1" in result.output
        content = open(out_path).read()
        assert "Period Comparison" in content

    def test_yoy_and_compare_period_are_mutually_exclusive(self, multi_period_csv, tmp_path):
        runner = CliRunner()
        out_path = str(tmp_path / "report.md")
        result = runner.invoke(
            cli,
            [
                "generate",
                "--framework",
                "dsa",
                "--period",
                "2024-H1",
                "--data",
                multi_period_csv,
                "--format",
                "markdown",
                "--output",
                out_path,
                "--yoy",
                "--compare-period",
                "2023-H1",
            ],
        )
        assert result.exit_code != 0

    def test_generate_yoy_missing_prior_data_warns(self, tmp_path):
        """When prior-year data is absent, comparison is omitted with a warning."""
        rows = [
            "metric_id,period,value",
            "notices_received,2024-H1,284750",
            "notices_actioned,2024-H1,213562",
            "complaints_received,2024-H1,47830",
            "complaints_reversed,2024-H1,6214",
            "content_moderation_orders_received,2024-H1,342",
            "notices_median_response_time,2024-H1,4.2",
        ]
        csv_path = tmp_path / "current_only.csv"
        csv_path.write_text("\n".join(rows))
        out_path = str(tmp_path / "report.md")

        runner = CliRunner()
        result = runner.invoke(
            cli,
            [
                "generate",
                "--framework",
                "dsa",
                "--period",
                "2024-H1",
                "--data",
                str(csv_path),
                "--format",
                "markdown",
                "--output",
                out_path,
                "--yoy",
            ],
        )
        assert result.exit_code == 0, result.output
        assert "Warning" in result.output
        content = open(out_path).read()
        assert "Period Comparison" not in content


class TestGenerateCLIQuiet:
    """Tests for --quiet / -q flag on the generate command."""

    @pytest.fixture
    def simple_csv(self, tmp_path):
        rows = [
            "metric_id,period,value",
            "notices_received,2024-H1,284750",
            "notices_actioned,2024-H1,213562",
            "complaints_received,2024-H1,47830",
            "complaints_reversed,2024-H1,6214",
            "content_moderation_orders_received,2024-H1,342",
            "notices_median_response_time,2024-H1,4.2",
        ]
        path = tmp_path / "metrics.csv"
        path.write_text("\n".join(rows))
        return str(path)

    @pytest.fixture
    def multi_period_csv(self, tmp_path):
        rows = [
            "metric_id,period,value",
            "notices_received,2024-H1,284750",
            "notices_actioned,2024-H1,213562",
            "complaints_received,2024-H1,47830",
            "notices_received,2023-H1,241000",
            "notices_actioned,2023-H1,180750",
        ]
        path = tmp_path / "metrics_multi.csv"
        path.write_text("\n".join(rows))
        return str(path)

    def test_quiet_suppresses_progress_messages(self, simple_csv, tmp_path):
        runner = CliRunner()
        out_path = str(tmp_path / "report.md")
        result = runner.invoke(
            cli,
            [
                "generate",
                "--framework",
                "dsa",
                "--period",
                "2024-H1",
                "--data",
                simple_csv,
                "--format",
                "markdown",
                "--output",
                out_path,
                "--quiet",
            ],
        )
        assert result.exit_code == 0, result.output
        assert result.output == ""

    def test_short_flag_q_also_works(self, simple_csv, tmp_path):
        runner = CliRunner()
        out_path = str(tmp_path / "report.md")
        result = runner.invoke(
            cli,
            [
                "generate",
                "--framework",
                "dsa",
                "--period",
                "2024-H1",
                "--data",
                simple_csv,
                "--format",
                "markdown",
                "--output",
                out_path,
                "-q",
            ],
        )
        assert result.exit_code == 0, result.output
        assert result.output == ""

    def test_quiet_still_shows_warnings(self, tmp_path):
        """--quiet does not suppress missing-data warnings."""
        rows = [
            "metric_id,period,value",
            "notices_received,2024-H1,284750",
            "complaints_received,2024-H1,47830",
        ]
        csv_path = tmp_path / "current_only.csv"
        csv_path.write_text("\n".join(rows))
        out_path = str(tmp_path / "report.md")

        runner = CliRunner()
        result = runner.invoke(
            cli,
            [
                "generate",
                "--framework",
                "dsa",
                "--period",
                "2024-H1",
                "--data",
                str(csv_path),
                "--format",
                "markdown",
                "--output",
                out_path,
                "--yoy",
                "--quiet",
            ],
        )
        assert result.exit_code == 0, result.output
        assert "Warning" in result.output

    def test_quiet_suppresses_yoy_info_line(self, multi_period_csv, tmp_path):
        """The 'Year-over-year comparison: ...' line is suppressed in quiet mode."""
        runner = CliRunner()
        out_path = str(tmp_path / "report.md")
        result = runner.invoke(
            cli,
            [
                "generate",
                "--framework",
                "dsa",
                "--period",
                "2024-H1",
                "--data",
                multi_period_csv,
                "--format",
                "markdown",
                "--output",
                out_path,
                "--yoy",
                "--quiet",
            ],
        )
        assert result.exit_code == 0, result.output
        assert "Year-over-year" not in result.output
        assert "Report written" not in result.output
        # The report itself should still be generated correctly
        content = open(out_path).read()
        assert "Period Comparison" in content

    def test_without_quiet_shows_progress(self, simple_csv, tmp_path):
        """Baseline: without --quiet the progress messages are present."""
        runner = CliRunner()
        out_path = str(tmp_path / "report.md")
        result = runner.invoke(
            cli,
            [
                "generate",
                "--framework",
                "dsa",
                "--period",
                "2024-H1",
                "--data",
                simple_csv,
                "--format",
                "markdown",
                "--output",
                out_path,
            ],
        )
        assert result.exit_code == 0, result.output
        assert "Generating" in result.output
        assert "Report written" in result.output
